import type { Metadata } from 'next'
import './globals.css'
import { poppins } from '@/lib/font'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${poppins.className} antialiased px-4 min-mobile:px-0`}>
        {children}
      </body>
    </html>
  )
}
